Backend/metrics
PolyCortex/polydodo pull request #63
Opened 2020-11-06 04:21 UTC by conorato

Return epochs, spectrograms and some field of metadata in the classification response

2020-11-06 04:49 UTC, WilliamHarvey97 commented
Since I did the review IRL, nothing to say about this. From what I understand, there is only the following on our way to complete the back-end:
- Be compatible with OpenBCI session data file AND Raw SD card file. Ensure it handles Ganglion and Cyton;
- Compute metrics about sleep stage;
- Tests edge cases input values to our endpoint.

2020-11-06 22:20 UTC, abelfodil requested changes
Commentaires mineurs

2020-11-06 22:20 UTC, abelfodil commented on backend/classification/request.py
> +    def validate(self):
I would call validate in the constructor (and make this private)

2020-11-07 13:56 UTC, abelfodil approved these changes

2020-11-07 18:08 UTC, merged