Validate signal
PolyCortex/polydodo pull request #65
Opened 2020-11-07 23:00 UTC by MouradLachhab

Looking for code and UI changes. Validation will have to be tested on someone eventually.

![image](https://user-images.githubusercontent.com/26387408/98453056-0cf6b980-2123-11eb-908b-b6ec9e429dc0.png)

2020-11-07 23:32 UTC, abelfodil commented
What if qu'on teste le signal continuellement pis qu'on bloque le "Next" tant que le signal est pas valide pendant genre au moins 5s ? Ça enlève le besoin de cliquer sur un bouton pour valider

2020-11-07 23:47 UTC, MouradLachhab commented
> What if qu'on teste le signal continuellement pis qu'on bloque le "Next" tant que le signal est pas valide pendant genre au moins 5s ? Ça enlève le besoin de cliquer sur un bouton pour valider

Sure yea, je vais voir ça demain mais ça devrait bien se faire.

2020-11-08 18:22 UTC, MouradLachhab commented
New UI using continuous validation.

![image](https://user-images.githubusercontent.com/26387408/98480369-82b36180-21c5-11eb-8bb7-2828b79ce705.png)

2020-11-08 23:27 UTC, abelfodil requested changes
Good work

2020-11-08 23:27 UTC, abelfodil commented on mobile/lib/src/application/eeg_data/data_cubit.dart
> +    }
`else if` et `else` plutot qu'un ternaire?

2020-11-08 23:27 UTC, abelfodil commented on mobile/lib/src/application/eeg_data/data_states.dart
> +  final SignalResult channelTwoResult;
les noms des actual channels

2020-11-08 23:27 UTC, abelfodil commented on mobile/lib/src/infrastructure/connection_repositories/eeg_data_repository.dart
> +  double _channelTwoMaxValue = 0;
actual names

2020-11-08 23:27 UTC, abelfodil commented on mobile/lib/src/infrastructure/connection_repositories/eeg_data_repository.dart
> +    }
Guard clause to minimize nesting

2020-11-08 23:27 UTC, abelfodil commented on mobile/lib/src/presentation/pages/record_sleep/signal_section.dart
> +        _buildSignalInformation('Pz-Oz', channelTwoResult)
actual channel names

2020-11-08 23:27 UTC, abelfodil commented on mobile/lib/src/presentation/pages/record_sleep/signal_section.dart
> +        _buildSignalInformation('Pz-Oz', channelTwoResult)
also, why are channelOneResult and channelTwoResult possibly uninit?

2020-11-09 19:32 UTC, abelfodil approved these changes

2020-11-09 20:06 UTC, merged