Merged view of usb and bluetooth devices
PolyCortex/polydodo pull request #81
Opened 2020-11-15 00:41 UTC by MouradLachhab

Showing Usb and Bluetooth devices in the same view. Also fixed a bug where plugging in a Usb device after opening the page wouldn't show it.

2020-11-15 15:27 UTC, abelfodil approved these changes

2020-11-15 23:10 UTC, WilliamHarvey97 requested changes

2020-11-15 23:58 UTC, WilliamHarvey97 requested changes

2020-11-15 23:58 UTC, WilliamHarvey97 commented on mobile/lib/src/infrastructure/connection_repositories/bluetooth_repository.dart
>    void initializeRepository() {
Pourquoi ne pas nommer cela scan()? On pourrait retourner `Stream<List<AcquisitionDevice>>` à la place de `void`?

2020-11-17 20:40 UTC, WilliamHarvey97 commented on mobile/lib/src/services/device_locator_service.dart
> +class DeviceLocatorService implements IDeviceLocatorService {
The service does not need to be implemented. A domain service can use domain objects only by using the repository interfaces.

2020-11-17 20:40 UTC, WilliamHarvey97 commented on mobile/lib/src/services/device_locator_service.dart
> +  final BluetoothRepository _bluetoothRepository = BluetoothRepository();
Could be injected in the domain layer in locator.dart

2020-11-17 20:40 UTC, WilliamHarvey97 commented on mobile/lib/src/application/device/device_selector_cubit.dart
> +  final List<AcquisitionDevice> _acquisitionDevicePersistency = [];
```suggestion
  final List<AcquisitionDevice> _scannedDevices = [];
```

2020-11-17 20:40 UTC, WilliamHarvey97 commented on mobile/lib/src/application/device/device_selector_cubit.dart
> +  final List<AcquisitionDevice> _acquisitionDevicePersistency = [];
ou encore _locatedDevices

2020-11-17 20:40 UTC, WilliamHarvey97 commented on mobile/lib/src/application/device/device_selector_cubit.dart
> +    _deviceLocatorStreamSubscription ??= _deviceLocatorStream.listen((devices) {
J'ai regardé un peu le code. Dans IAcquisitionDevice::scan() on pourrait simplement retourner stream<Scan> et les accumuler dans notre tableau ici, cela simplifierait beaucoup le code non?

2020-11-19 01:48 UTC, WilliamHarvey97 approved these changes

2020-11-19 01:48 UTC, WilliamHarvey97 commented on mobile/lib/src/domain/acquisition_device/device_locator_service.dart
> +import 'package:polydodo/src/infrastructure/connection_repositories/bluetooth_repository.dart';
Il faut utiliser les interfaces et non pas l'implémentation. La couche de domaine ne se connaît seulement qu'elle même

2020-11-19 01:48 UTC, WilliamHarvey97 commented on mobile/lib/src/application/device/device_selector_cubit.dart
> +      _scannedDevices[idx] = device;
Est-ce qu'on a vraiment besoin de changer le device? Si le device reste toujours pareil, on peut plutôt faire:

```dart
if (!_scannedDevices.contains(device)) {
    _scannedDevices.add(device);
}
```

2020-11-19 01:48 UTC, WilliamHarvey97 commented on mobile/lib/src/domain/acquisition_device/device_locator_service.dart
> +import 'package:polydodo/src/infrastructure/connection_repositories/bluetooth_repository.dart';
On pourra injecter les implémentation dans le constructeur de `DeviceLocatorService` dans `locator.dart`

2020-11-19 01:48 UTC, WilliamHarvey97 commented on mobile/lib/src/infrastructure/connection_repositories/bluetooth_repository.dart
>    void addDevice(DiscoveredDevice bluetoothDevice) {
```suggestion
  void _addDevice(DiscoveredDevice bluetoothDevice) {
```

2020-11-19 01:48 UTC, WilliamHarvey97 commented on mobile/lib/src/infrastructure/connection_repositories/bluetooth_repository.dart
> +        .scanForDevices(withServices: []).listen((device) => addDevice(device));
à la place d'utiliser listen et addDevice, on pourrait utiliser plutôt un map. On aurait plus besoin d'utiliser un stream controller et le code serait encore plus simple.

```suggestion
        .scanForDevices(withServices: []).map((device) => AcquisitionDevice(
            UniqueId.from(bluetoothDevice.id),
            (bluetoothDevice.name.isEmpty) ? 'Unknown' : bluetoothDevice.name,
            DeviceType.bluetooth,
        );
```

2020-11-19 01:53 UTC, MouradLachhab commented on mobile/lib/src/domain/acquisition_device/device_locator_service.dart
> +import 'package:polydodo/src/infrastructure/connection_repositories/bluetooth_repository.dart';
Oops, en effet.

2020-11-19 17:34 UTC, merged