Backend/add logs
PolyCortex/polydodo pull request #86
Opened 2020-11-16 01:38 UTC by conorato

![Capture d’écran, le 2020-11-15 à 20 36 52](https://user-images.githubusercontent.com/17006104/99204085-89704480-2782-11eb-93d5-e3304127d97a.png)

2020-11-16 04:05 UTC, abelfodil commented on backend/config/logging.py
> +    return console_handler
C'est surement juste une question de gout, mais moi je trouve ça confusing le tab de plus.

Par expérience, je vois des tab à l'intérieur d'une entrée même (exemple un callstack sur plusieurs lignes, chaque ligne du callstack sera tabulée).

2020-11-16 04:16 UTC, abelfodil requested changes
Good job! Les messages sont vraiment informatifs.

2020-11-16 04:16 UTC, abelfodil commented on backend/classification/load_model.py
> +            f"This could take a few minutes. (storing it to {MODEL_PATH})"
```suggestion
            f"This could take a few minutes. (storing it at {MODEL_PATH})"
```

2020-11-16 04:16 UTC, abelfodil commented on backend/classification/load_model.py
> +            _logger.info(f"Downloading postprocessing model... (storing it to {model_path})")
```suggestion
            _logger.info(f"Downloading postprocessing model... (storing it at {model_path})")
```

2020-11-16 04:16 UTC, abelfodil commented on backend/config/logging.py
> +STD_OUTPUT_FORMAT = "[%(asctime)s]:\t%(levelname)s\t%(message)s (%(name)s)"
```suggestion
STD_OUTPUT_FORMAT = "[%(asctime)s]: [%(levelname)s] %(message)s (%(name)s)"
```

Plus compact

2020-11-16 04:16 UTC, abelfodil commented on backend/backend/analyze_sleep.py
> +            _logger.warn(
error?

2020-11-16 19:50 UTC, conorato commented on backend/backend/analyze_sleep.py
> +            _logger.warn(
Comme c'est un erreur dans la requête, je ne voulais pas mettre error, afin d'éviter que l'utilisateur pense que le serveur ne fonctionne pas et qu'il y ait eu un internal server error.

2020-11-16 19:58 UTC, conorato commented on backend/config/logging.py
> +    return console_handler
Comme les logs vont être lu du côté utilisateur, j'ai préféré mettre des tabs pour représenter les sous-étapes de la requête. Dans le cas où je ne mettais pas de tab, je trouvais que c'était difficile de suivre le flow des étapes. Je ne crois pas qu'on pourrait le confondre avec un erreur, comme on indique le loglevel

2020-11-17 01:44 UTC, abelfodil approved these changes

2020-11-17 20:31 UTC, merged